#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App.Resource", IsApplication=true)]

namespace App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040005
			public const int accent = 2130968581;
			
			// aapt resource value: 0x7f04001f
			public const int backgroundFotoAnuncio = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public const int blueButton = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int blueButtonPressed = 2130968590;
			
			// aapt resource value: 0x7f040008
			public const int blueGradientEnd = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int blueGradientStart = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int blueMessage = 2130968586;
			
			// aapt resource value: 0x7f04000f
			public const int clearButton = 2130968591;
			
			// aapt resource value: 0x7f040004
			public const int colorControlNormal = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int defaultBackground = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int divider = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int grayButton = 2130968592;
			
			// aapt resource value: 0x7f040009
			public const int grayMessage = 2130968585;
			
			// aapt resource value: 0x7f040011
			public const int grayPressedButton = 2130968593;
			
			// aapt resource value: 0x7f04001c
			public const int greyBackgroundTransparent = 2130968604;
			
			// aapt resource value: 0x7f040014
			public const int hintColor = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int labelColor = 2130968597;
			
			// aapt resource value: 0x7f040018
			public const int preto = 2130968600;
			
			// aapt resource value: 0x7f040000
			public const int primaryColor = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int primaryDark = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int primaryText = 2130968578;
			
			// aapt resource value: 0x7f040012
			public const int redButton = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int redPressedButton = 2130968595;
			
			// aapt resource value: 0x7f040003
			public const int secondaryText = 2130968579;
			
			// aapt resource value: 0x7f040020
			public const int textSilverColor = 2130968608;
			
			// aapt resource value: 0x7f04001a
			public const int textoAnuncioVendaTrocaDoacaoAtivo = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int textoAnuncioVendaTrocaDoacaoInativo = 2130968603;
			
			// aapt resource value: 0x7f04001e
			public const int textoCaracteristicasAdicionaisDesabilitado = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int textoCaracteristicasAdicionaisHabilitado = 2130968605;
			
			// aapt resource value: 0x7f040017
			public const int transparent = 2130968599;
			
			// aapt resource value: 0x7f040019
			public const int views = 2130968601;
			
			// aapt resource value: 0x7f040016
			public const int whiteButtonPressed = 2130968598;
			
			// aapt resource value: 0x7f040006
			public const int window_background = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BordedLinearLayout = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int LinearSemID = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int List = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int fragmentContainer = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int linearItemAnuncio = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int mnExit = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int mnRefresh = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int progressBar = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int textView = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int txtLastRefresh = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int txtTime = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdapterItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Tab = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TabList = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
