//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainTimeResult
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.irishrail.ie/realtime/", ConfigurationName="TrainTimeResult.RealtimeSoap")]
    public interface RealtimeSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getAllStationsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.objStation[]> getAllStationsXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getAllStationsXML_WithStationType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.getAllStationsXML_WithStationType1> getAllStationsXML1Async(TrainTimeResult.getAllStationsXML_WithStationType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getHaconTrainsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.objHaconPositions[]> getHaconTrainsXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getCurrentTrainsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.objTrainPositions[]> getCurrentTrainsXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getCurrentTrainsXML_WithTrainType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.getCurrentTrainsXML_WithTrainType1> getCurrentTrainsXML1Async(TrainTimeResult.getCurrentTrainsXML_WithTrainType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByNameXML_withNumMins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.getStationDataByNameXML_withNumMins1> getStationDataByNameXMLAsync(TrainTimeResult.getStationDataByNameXML_withNumMins request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByNameXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.getStationDataByNameXMLResponse> getStationDataByNameXML1Async(TrainTimeResult.getStationDataByNameXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByCodeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.objStationData[]> getStationDataByCodeXMLAsync(string StationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByCodeXML_WithNumMins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.getStationDataByCodeXML_WithNumMins1> getStationDataByCodeXML1Async(TrainTimeResult.getStationDataByCodeXML_WithNumMins request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationsFilterXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.objStationFilter[]> getStationsFilterXMLAsync(string StationText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getTrainMovementsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TrainTimeResult.objTrainMovements[]> getTrainMovementsXMLAsync(string TrainId, string TrainDate);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objStation
    {
        
        private string stationDescField;
        
        private string stationAliasField;
        
        private string stationLatitudeField;
        
        private string stationLongitudeField;
        
        private string stationCodeField;
        
        private string stationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StationDesc
        {
            get
            {
                return this.stationDescField;
            }
            set
            {
                this.stationDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StationAlias
        {
            get
            {
                return this.stationAliasField;
            }
            set
            {
                this.stationAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StationLatitude
        {
            get
            {
                return this.stationLatitudeField;
            }
            set
            {
                this.stationLatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StationLongitude
        {
            get
            {
                return this.stationLongitudeField;
            }
            set
            {
                this.stationLongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StationCode
        {
            get
            {
                return this.stationCodeField;
            }
            set
            {
                this.stationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StationId
        {
            get
            {
                return this.stationIdField;
            }
            set
            {
                this.stationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objTrainMovements
    {
        
        private string trainCodeField;
        
        private string trainDateField;
        
        private string locationCodeField;
        
        private string locationFullNameField;
        
        private string locationOrderField;
        
        private string locationTypeField;
        
        private string trainOriginField;
        
        private string trainDestinationField;
        
        private string scheduledArrivalField;
        
        private string scheduledDepartureField;
        
        private string expectedArrivalField;
        
        private string expectedDepartureField;
        
        private string arrivalField;
        
        private string departureField;
        
        private string autoArrivalField;
        
        private string autoDepartField;
        
        private string stopTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TrainCode
        {
            get
            {
                return this.trainCodeField;
            }
            set
            {
                this.trainCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TrainDate
        {
            get
            {
                return this.trainDateField;
            }
            set
            {
                this.trainDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LocationCode
        {
            get
            {
                return this.locationCodeField;
            }
            set
            {
                this.locationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LocationFullName
        {
            get
            {
                return this.locationFullNameField;
            }
            set
            {
                this.locationFullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LocationOrder
        {
            get
            {
                return this.locationOrderField;
            }
            set
            {
                this.locationOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LocationType
        {
            get
            {
                return this.locationTypeField;
            }
            set
            {
                this.locationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TrainOrigin
        {
            get
            {
                return this.trainOriginField;
            }
            set
            {
                this.trainOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TrainDestination
        {
            get
            {
                return this.trainDestinationField;
            }
            set
            {
                this.trainDestinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ScheduledArrival
        {
            get
            {
                return this.scheduledArrivalField;
            }
            set
            {
                this.scheduledArrivalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ScheduledDeparture
        {
            get
            {
                return this.scheduledDepartureField;
            }
            set
            {
                this.scheduledDepartureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ExpectedArrival
        {
            get
            {
                return this.expectedArrivalField;
            }
            set
            {
                this.expectedArrivalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ExpectedDeparture
        {
            get
            {
                return this.expectedDepartureField;
            }
            set
            {
                this.expectedDepartureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Arrival
        {
            get
            {
                return this.arrivalField;
            }
            set
            {
                this.arrivalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Departure
        {
            get
            {
                return this.departureField;
            }
            set
            {
                this.departureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AutoArrival
        {
            get
            {
                return this.autoArrivalField;
            }
            set
            {
                this.autoArrivalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AutoDepart
        {
            get
            {
                return this.autoDepartField;
            }
            set
            {
                this.autoDepartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string StopType
        {
            get
            {
                return this.stopTypeField;
            }
            set
            {
                this.stopTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objStationFilter
    {
        
        private string stationDesc_spField;
        
        private string stationDescField;
        
        private string stationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StationDesc_sp
        {
            get
            {
                return this.stationDesc_spField;
            }
            set
            {
                this.stationDesc_spField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StationDesc
        {
            get
            {
                return this.stationDescField;
            }
            set
            {
                this.stationDescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StationCode
        {
            get
            {
                return this.stationCodeField;
            }
            set
            {
                this.stationCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objStationData
    {
        
        private System.DateTime servertimeField;
        
        private string traincodeField;
        
        private string stationfullnameField;
        
        private string stationcodeField;
        
        private string querytimeField;
        
        private string traindateField;
        
        private string originField;
        
        private string destinationField;
        
        private string origintimeField;
        
        private string destinationtimeField;
        
        private string statusField;
        
        private string lastlocationField;
        
        private int dueinField;
        
        private int lateField;
        
        private string exparrivalField;
        
        private string expdepartField;
        
        private string scharrivalField;
        
        private string schdepartField;
        
        private string directionField;
        
        private string traintypeField;
        
        private string locationtypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Servertime
        {
            get
            {
                return this.servertimeField;
            }
            set
            {
                this.servertimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Traincode
        {
            get
            {
                return this.traincodeField;
            }
            set
            {
                this.traincodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Stationfullname
        {
            get
            {
                return this.stationfullnameField;
            }
            set
            {
                this.stationfullnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Stationcode
        {
            get
            {
                return this.stationcodeField;
            }
            set
            {
                this.stationcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Querytime
        {
            get
            {
                return this.querytimeField;
            }
            set
            {
                this.querytimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Traindate
        {
            get
            {
                return this.traindateField;
            }
            set
            {
                this.traindateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Origintime
        {
            get
            {
                return this.origintimeField;
            }
            set
            {
                this.origintimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Destinationtime
        {
            get
            {
                return this.destinationtimeField;
            }
            set
            {
                this.destinationtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Lastlocation
        {
            get
            {
                return this.lastlocationField;
            }
            set
            {
                this.lastlocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int Duein
        {
            get
            {
                return this.dueinField;
            }
            set
            {
                this.dueinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Late
        {
            get
            {
                return this.lateField;
            }
            set
            {
                this.lateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Exparrival
        {
            get
            {
                return this.exparrivalField;
            }
            set
            {
                this.exparrivalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Expdepart
        {
            get
            {
                return this.expdepartField;
            }
            set
            {
                this.expdepartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Scharrival
        {
            get
            {
                return this.scharrivalField;
            }
            set
            {
                this.scharrivalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Schdepart
        {
            get
            {
                return this.schdepartField;
            }
            set
            {
                this.schdepartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Traintype
        {
            get
            {
                return this.traintypeField;
            }
            set
            {
                this.traintypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Locationtype
        {
            get
            {
                return this.locationtypeField;
            }
            set
            {
                this.locationtypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objTrainPositions
    {
        
        private string trainStatusField;
        
        private string trainLatitudeField;
        
        private string trainLongitudeField;
        
        private string trainCodeField;
        
        private string trainDateField;
        
        private string publicMessageField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TrainStatus
        {
            get
            {
                return this.trainStatusField;
            }
            set
            {
                this.trainStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TrainLatitude
        {
            get
            {
                return this.trainLatitudeField;
            }
            set
            {
                this.trainLatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TrainLongitude
        {
            get
            {
                return this.trainLongitudeField;
            }
            set
            {
                this.trainLongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TrainCode
        {
            get
            {
                return this.trainCodeField;
            }
            set
            {
                this.trainCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TrainDate
        {
            get
            {
                return this.trainDateField;
            }
            set
            {
                this.trainDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PublicMessage
        {
            get
            {
                return this.publicMessageField;
            }
            set
            {
                this.publicMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objHaconPositions
    {
        
        private string trainStatusField;
        
        private string trainLatitudeField;
        
        private string trainLongitudeField;
        
        private string trainCodeField;
        
        private string trainDateField;
        
        private string lastLocationTypeField;
        
        private string directionField;
        
        private string trainOriginField;
        
        private string trainOriginTimeField;
        
        private string trainDestinationField;
        
        private string trainDestinationTimeField;
        
        private string lastLocationField;
        
        private string nextLocationField;
        
        private string differenceField;
        
        private string scheduledDepartureField;
        
        private string scheduledArrivalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TrainStatus
        {
            get
            {
                return this.trainStatusField;
            }
            set
            {
                this.trainStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TrainLatitude
        {
            get
            {
                return this.trainLatitudeField;
            }
            set
            {
                this.trainLatitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TrainLongitude
        {
            get
            {
                return this.trainLongitudeField;
            }
            set
            {
                this.trainLongitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TrainCode
        {
            get
            {
                return this.trainCodeField;
            }
            set
            {
                this.trainCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TrainDate
        {
            get
            {
                return this.trainDateField;
            }
            set
            {
                this.trainDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastLocationType
        {
            get
            {
                return this.lastLocationTypeField;
            }
            set
            {
                this.lastLocationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TrainOrigin
        {
            get
            {
                return this.trainOriginField;
            }
            set
            {
                this.trainOriginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TrainOriginTime
        {
            get
            {
                return this.trainOriginTimeField;
            }
            set
            {
                this.trainOriginTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TrainDestination
        {
            get
            {
                return this.trainDestinationField;
            }
            set
            {
                this.trainDestinationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TrainDestinationTime
        {
            get
            {
                return this.trainDestinationTimeField;
            }
            set
            {
                this.trainDestinationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LastLocation
        {
            get
            {
                return this.lastLocationField;
            }
            set
            {
                this.lastLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string NextLocation
        {
            get
            {
                return this.nextLocationField;
            }
            set
            {
                this.nextLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Difference
        {
            get
            {
                return this.differenceField;
            }
            set
            {
                this.differenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ScheduledDeparture
        {
            get
            {
                return this.scheduledDepartureField;
            }
            set
            {
                this.scheduledDepartureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ScheduledArrival
        {
            get
            {
                return this.scheduledArrivalField;
            }
            set
            {
                this.scheduledArrivalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllStationsXML_WithStationType", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getAllStationsXML_WithStationType
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public string StationType;
        
        public getAllStationsXML_WithStationType()
        {
        }
        
        public getAllStationsXML_WithStationType(string StationType)
        {
            this.StationType = StationType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllStationsXML_WithStationTypeResponse", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getAllStationsXML_WithStationType1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public TrainTimeResult.objStation[] getAllStationsXML_WithStationTypeResult;
        
        public getAllStationsXML_WithStationType1()
        {
        }
        
        public getAllStationsXML_WithStationType1(TrainTimeResult.objStation[] getAllStationsXML_WithStationTypeResult)
        {
            this.getAllStationsXML_WithStationTypeResult = getAllStationsXML_WithStationTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentTrainsXML_WithTrainType", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getCurrentTrainsXML_WithTrainType
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public string TrainType;
        
        public getCurrentTrainsXML_WithTrainType()
        {
        }
        
        public getCurrentTrainsXML_WithTrainType(string TrainType)
        {
            this.TrainType = TrainType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentTrainsXML_WithTrainTypeResponse", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getCurrentTrainsXML_WithTrainType1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public TrainTimeResult.objTrainPositions[] getCurrentTrainsXML_WithTrainTypeResult;
        
        public getCurrentTrainsXML_WithTrainType1()
        {
        }
        
        public getCurrentTrainsXML_WithTrainType1(TrainTimeResult.objTrainPositions[] getCurrentTrainsXML_WithTrainTypeResult)
        {
            this.getCurrentTrainsXML_WithTrainTypeResult = getCurrentTrainsXML_WithTrainTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByNameXML_withNumMins", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByNameXML_withNumMins
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public string StationDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=1)]
        public string NumMins;
        
        public getStationDataByNameXML_withNumMins()
        {
        }
        
        public getStationDataByNameXML_withNumMins(string StationDesc, string NumMins)
        {
            this.StationDesc = StationDesc;
            this.NumMins = NumMins;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByNameXML_withNumMinsResponse", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByNameXML_withNumMins1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public TrainTimeResult.objStationData[] getStationDataByNameXML_withNumMinsResult;
        
        public getStationDataByNameXML_withNumMins1()
        {
        }
        
        public getStationDataByNameXML_withNumMins1(TrainTimeResult.objStationData[] getStationDataByNameXML_withNumMinsResult)
        {
            this.getStationDataByNameXML_withNumMinsResult = getStationDataByNameXML_withNumMinsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByNameXML", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByNameXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public string StationDesc;
        
        public getStationDataByNameXMLRequest()
        {
        }
        
        public getStationDataByNameXMLRequest(string StationDesc)
        {
            this.StationDesc = StationDesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByNameXMLResponse", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByNameXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public TrainTimeResult.objStationData[] getStationDataByNameXMLResult;
        
        public getStationDataByNameXMLResponse()
        {
        }
        
        public getStationDataByNameXMLResponse(TrainTimeResult.objStationData[] getStationDataByNameXMLResult)
        {
            this.getStationDataByNameXMLResult = getStationDataByNameXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByCodeXML_WithNumMins", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByCodeXML_WithNumMins
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public string StationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=1)]
        public string NumMins;
        
        public getStationDataByCodeXML_WithNumMins()
        {
        }
        
        public getStationDataByCodeXML_WithNumMins(string StationCode, string NumMins)
        {
            this.StationCode = StationCode;
            this.NumMins = NumMins;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByCodeXML_WithNumMinsResponse", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByCodeXML_WithNumMins1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public TrainTimeResult.objStationData[] getStationDataByCodeXML_WithNumMinsResult;
        
        public getStationDataByCodeXML_WithNumMins1()
        {
        }
        
        public getStationDataByCodeXML_WithNumMins1(TrainTimeResult.objStationData[] getStationDataByCodeXML_WithNumMinsResult)
        {
            this.getStationDataByCodeXML_WithNumMinsResult = getStationDataByCodeXML_WithNumMinsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface RealtimeSoapChannel : TrainTimeResult.RealtimeSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class RealtimeSoapClient : System.ServiceModel.ClientBase<TrainTimeResult.RealtimeSoap>, TrainTimeResult.RealtimeSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RealtimeSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(RealtimeSoapClient.GetBindingForEndpoint(endpointConfiguration), RealtimeSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealtimeSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RealtimeSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealtimeSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RealtimeSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RealtimeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.objStation[]> getAllStationsXMLAsync()
        {
            return base.Channel.getAllStationsXMLAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainTimeResult.getAllStationsXML_WithStationType1> TrainTimeResult.RealtimeSoap.getAllStationsXML1Async(TrainTimeResult.getAllStationsXML_WithStationType request)
        {
            return base.Channel.getAllStationsXML1Async(request);
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.getAllStationsXML_WithStationType1> getAllStationsXML1Async(string StationType)
        {
            TrainTimeResult.getAllStationsXML_WithStationType inValue = new TrainTimeResult.getAllStationsXML_WithStationType();
            inValue.StationType = StationType;
            return ((TrainTimeResult.RealtimeSoap)(this)).getAllStationsXML1Async(inValue);
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.objHaconPositions[]> getHaconTrainsXMLAsync()
        {
            return base.Channel.getHaconTrainsXMLAsync();
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.objTrainPositions[]> getCurrentTrainsXMLAsync()
        {
            return base.Channel.getCurrentTrainsXMLAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainTimeResult.getCurrentTrainsXML_WithTrainType1> TrainTimeResult.RealtimeSoap.getCurrentTrainsXML1Async(TrainTimeResult.getCurrentTrainsXML_WithTrainType request)
        {
            return base.Channel.getCurrentTrainsXML1Async(request);
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.getCurrentTrainsXML_WithTrainType1> getCurrentTrainsXML1Async(string TrainType)
        {
            TrainTimeResult.getCurrentTrainsXML_WithTrainType inValue = new TrainTimeResult.getCurrentTrainsXML_WithTrainType();
            inValue.TrainType = TrainType;
            return ((TrainTimeResult.RealtimeSoap)(this)).getCurrentTrainsXML1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainTimeResult.getStationDataByNameXML_withNumMins1> TrainTimeResult.RealtimeSoap.getStationDataByNameXMLAsync(TrainTimeResult.getStationDataByNameXML_withNumMins request)
        {
            return base.Channel.getStationDataByNameXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.getStationDataByNameXML_withNumMins1> getStationDataByNameXMLAsync(string StationDesc, string NumMins)
        {
            TrainTimeResult.getStationDataByNameXML_withNumMins inValue = new TrainTimeResult.getStationDataByNameXML_withNumMins();
            inValue.StationDesc = StationDesc;
            inValue.NumMins = NumMins;
            return ((TrainTimeResult.RealtimeSoap)(this)).getStationDataByNameXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainTimeResult.getStationDataByNameXMLResponse> TrainTimeResult.RealtimeSoap.getStationDataByNameXML1Async(TrainTimeResult.getStationDataByNameXMLRequest request)
        {
            return base.Channel.getStationDataByNameXML1Async(request);
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.getStationDataByNameXMLResponse> getStationDataByNameXML1Async(string StationDesc)
        {
            TrainTimeResult.getStationDataByNameXMLRequest inValue = new TrainTimeResult.getStationDataByNameXMLRequest();
            inValue.StationDesc = StationDesc;
            return ((TrainTimeResult.RealtimeSoap)(this)).getStationDataByNameXML1Async(inValue);
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.objStationData[]> getStationDataByCodeXMLAsync(string StationCode)
        {
            return base.Channel.getStationDataByCodeXMLAsync(StationCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TrainTimeResult.getStationDataByCodeXML_WithNumMins1> TrainTimeResult.RealtimeSoap.getStationDataByCodeXML1Async(TrainTimeResult.getStationDataByCodeXML_WithNumMins request)
        {
            return base.Channel.getStationDataByCodeXML1Async(request);
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.getStationDataByCodeXML_WithNumMins1> getStationDataByCodeXML1Async(string StationCode, string NumMins)
        {
            TrainTimeResult.getStationDataByCodeXML_WithNumMins inValue = new TrainTimeResult.getStationDataByCodeXML_WithNumMins();
            inValue.StationCode = StationCode;
            inValue.NumMins = NumMins;
            return ((TrainTimeResult.RealtimeSoap)(this)).getStationDataByCodeXML1Async(inValue);
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.objStationFilter[]> getStationsFilterXMLAsync(string StationText)
        {
            return base.Channel.getStationsFilterXMLAsync(StationText);
        }
        
        public System.Threading.Tasks.Task<TrainTimeResult.objTrainMovements[]> getTrainMovementsXMLAsync(string TrainId, string TrainDate)
        {
            return base.Channel.getTrainMovementsXMLAsync(TrainId, TrainDate);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RealtimeSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.RealtimeSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RealtimeSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://api.irishrail.ie/realtime/realtime.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.RealtimeSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://api.irishrail.ie/realtime/realtime.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            RealtimeSoap,
            
            RealtimeSoap12,
        }
    }
}
