//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusGoBackHome.TrainTimeResult {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.irishrail.ie/realtime/", ConfigurationName="TrainTimeResult.RealtimeSoap")]
    public interface RealtimeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getAllStationsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.objStation[] getAllStationsXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getAllStationsXML", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objStation[]> getAllStationsXMLAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (getAllStationsXML_WithStationType) of message getAllStationsXML_WithStationType does not match the default value (getAllStationsXML1)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getAllStationsXML_WithStationType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType1 getAllStationsXML1(BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getAllStationsXML_WithStationType", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType1> getAllStationsXML1Async(BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getHaconTrainsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.objHaconPositions[] getHaconTrainsXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getHaconTrainsXML", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objHaconPositions[]> getHaconTrainsXMLAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getCurrentTrainsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.objTrainPositions[] getCurrentTrainsXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getCurrentTrainsXML", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objTrainPositions[]> getCurrentTrainsXMLAsync();
        
        // CODEGEN: Generating message contract since the wrapper name (getCurrentTrainsXML_WithTrainType) of message getCurrentTrainsXML_WithTrainType does not match the default value (getCurrentTrainsXML1)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getCurrentTrainsXML_WithTrainType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType1 getCurrentTrainsXML1(BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getCurrentTrainsXML_WithTrainType", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType1> getCurrentTrainsXML1Async(BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType request);
        
        // CODEGEN: Generating message contract since the wrapper name (getStationDataByNameXML_withNumMins) of message getStationDataByNameXML_withNumMins does not match the default value (getStationDataByNameXML)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByNameXML_withNumMins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins1 getStationDataByNameXML(BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByNameXML_withNumMins", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins1> getStationDataByNameXMLAsync(BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins request);
        
        // CODEGEN: Generating message contract since the wrapper name (getStationDataByNameXML) of message getStationDataByNameXMLRequest does not match the default value (getStationDataByNameXML1)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByNameXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.getStationDataByNameXMLResponse getStationDataByNameXML1(BusGoBackHome.TrainTimeResult.getStationDataByNameXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByNameXML", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getStationDataByNameXMLResponse> getStationDataByNameXML1Async(BusGoBackHome.TrainTimeResult.getStationDataByNameXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByCodeXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByCodeXML(string StationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByCodeXML", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objStationData[]> getStationDataByCodeXMLAsync(string StationCode);
        
        // CODEGEN: Generating message contract since the wrapper name (getStationDataByCodeXML_WithNumMins) of message getStationDataByCodeXML_WithNumMins does not match the default value (getStationDataByCodeXML1)
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByCodeXML_WithNumMins", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins1 getStationDataByCodeXML1(BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationDataByCodeXML_WithNumMins", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins1> getStationDataByCodeXML1Async(BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationsFilterXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.objStationFilter[] getStationsFilterXML(string StationText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getStationsFilterXML", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objStationFilter[]> getStationsFilterXMLAsync(string StationText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getTrainMovementsXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BusGoBackHome.TrainTimeResult.objTrainMovements[] getTrainMovementsXML(string TrainId, string TrainDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.irishrail.ie/realtime/getTrainMovementsXML", ReplyAction="*")]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objTrainMovements[]> getTrainMovementsXMLAsync(string TrainId, string TrainDate);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objStation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stationDescField;
        
        private string stationAliasField;
        
        private string stationLatitudeField;
        
        private string stationLongitudeField;
        
        private string stationCodeField;
        
        private string stationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StationDesc {
            get {
                return this.stationDescField;
            }
            set {
                this.stationDescField = value;
                this.RaisePropertyChanged("StationDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StationAlias {
            get {
                return this.stationAliasField;
            }
            set {
                this.stationAliasField = value;
                this.RaisePropertyChanged("StationAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StationLatitude {
            get {
                return this.stationLatitudeField;
            }
            set {
                this.stationLatitudeField = value;
                this.RaisePropertyChanged("StationLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StationLongitude {
            get {
                return this.stationLongitudeField;
            }
            set {
                this.stationLongitudeField = value;
                this.RaisePropertyChanged("StationLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StationCode {
            get {
                return this.stationCodeField;
            }
            set {
                this.stationCodeField = value;
                this.RaisePropertyChanged("StationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StationId {
            get {
                return this.stationIdField;
            }
            set {
                this.stationIdField = value;
                this.RaisePropertyChanged("StationId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objTrainMovements : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string trainCodeField;
        
        private string trainDateField;
        
        private string locationCodeField;
        
        private string locationFullNameField;
        
        private string locationOrderField;
        
        private string locationTypeField;
        
        private string trainOriginField;
        
        private string trainDestinationField;
        
        private string scheduledArrivalField;
        
        private string scheduledDepartureField;
        
        private string expectedArrivalField;
        
        private string expectedDepartureField;
        
        private string arrivalField;
        
        private string departureField;
        
        private string autoArrivalField;
        
        private string autoDepartField;
        
        private string stopTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TrainCode {
            get {
                return this.trainCodeField;
            }
            set {
                this.trainCodeField = value;
                this.RaisePropertyChanged("TrainCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TrainDate {
            get {
                return this.trainDateField;
            }
            set {
                this.trainDateField = value;
                this.RaisePropertyChanged("TrainDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
                this.RaisePropertyChanged("LocationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LocationFullName {
            get {
                return this.locationFullNameField;
            }
            set {
                this.locationFullNameField = value;
                this.RaisePropertyChanged("LocationFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LocationOrder {
            get {
                return this.locationOrderField;
            }
            set {
                this.locationOrderField = value;
                this.RaisePropertyChanged("LocationOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LocationType {
            get {
                return this.locationTypeField;
            }
            set {
                this.locationTypeField = value;
                this.RaisePropertyChanged("LocationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TrainOrigin {
            get {
                return this.trainOriginField;
            }
            set {
                this.trainOriginField = value;
                this.RaisePropertyChanged("TrainOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TrainDestination {
            get {
                return this.trainDestinationField;
            }
            set {
                this.trainDestinationField = value;
                this.RaisePropertyChanged("TrainDestination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ScheduledArrival {
            get {
                return this.scheduledArrivalField;
            }
            set {
                this.scheduledArrivalField = value;
                this.RaisePropertyChanged("ScheduledArrival");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ScheduledDeparture {
            get {
                return this.scheduledDepartureField;
            }
            set {
                this.scheduledDepartureField = value;
                this.RaisePropertyChanged("ScheduledDeparture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ExpectedArrival {
            get {
                return this.expectedArrivalField;
            }
            set {
                this.expectedArrivalField = value;
                this.RaisePropertyChanged("ExpectedArrival");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ExpectedDeparture {
            get {
                return this.expectedDepartureField;
            }
            set {
                this.expectedDepartureField = value;
                this.RaisePropertyChanged("ExpectedDeparture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Arrival {
            get {
                return this.arrivalField;
            }
            set {
                this.arrivalField = value;
                this.RaisePropertyChanged("Arrival");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Departure {
            get {
                return this.departureField;
            }
            set {
                this.departureField = value;
                this.RaisePropertyChanged("Departure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AutoArrival {
            get {
                return this.autoArrivalField;
            }
            set {
                this.autoArrivalField = value;
                this.RaisePropertyChanged("AutoArrival");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AutoDepart {
            get {
                return this.autoDepartField;
            }
            set {
                this.autoDepartField = value;
                this.RaisePropertyChanged("AutoDepart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string StopType {
            get {
                return this.stopTypeField;
            }
            set {
                this.stopTypeField = value;
                this.RaisePropertyChanged("StopType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objStationFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stationDesc_spField;
        
        private string stationDescField;
        
        private string stationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StationDesc_sp {
            get {
                return this.stationDesc_spField;
            }
            set {
                this.stationDesc_spField = value;
                this.RaisePropertyChanged("StationDesc_sp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StationDesc {
            get {
                return this.stationDescField;
            }
            set {
                this.stationDescField = value;
                this.RaisePropertyChanged("StationDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StationCode {
            get {
                return this.stationCodeField;
            }
            set {
                this.stationCodeField = value;
                this.RaisePropertyChanged("StationCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objStationData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime servertimeField;
        
        private string traincodeField;
        
        private string stationfullnameField;
        
        private string stationcodeField;
        
        private string querytimeField;
        
        private string traindateField;
        
        private string originField;
        
        private string destinationField;
        
        private string origintimeField;
        
        private string destinationtimeField;
        
        private string statusField;
        
        private string lastlocationField;
        
        private int dueinField;
        
        private int lateField;
        
        private string exparrivalField;
        
        private string expdepartField;
        
        private string scharrivalField;
        
        private string schdepartField;
        
        private string directionField;
        
        private string traintypeField;
        
        private string locationtypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Servertime {
            get {
                return this.servertimeField;
            }
            set {
                this.servertimeField = value;
                this.RaisePropertyChanged("Servertime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Traincode {
            get {
                return this.traincodeField;
            }
            set {
                this.traincodeField = value;
                this.RaisePropertyChanged("Traincode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Stationfullname {
            get {
                return this.stationfullnameField;
            }
            set {
                this.stationfullnameField = value;
                this.RaisePropertyChanged("Stationfullname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Stationcode {
            get {
                return this.stationcodeField;
            }
            set {
                this.stationcodeField = value;
                this.RaisePropertyChanged("Stationcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Querytime {
            get {
                return this.querytimeField;
            }
            set {
                this.querytimeField = value;
                this.RaisePropertyChanged("Querytime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Traindate {
            get {
                return this.traindateField;
            }
            set {
                this.traindateField = value;
                this.RaisePropertyChanged("Traindate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
                this.RaisePropertyChanged("Origin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("Destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Origintime {
            get {
                return this.origintimeField;
            }
            set {
                this.origintimeField = value;
                this.RaisePropertyChanged("Origintime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Destinationtime {
            get {
                return this.destinationtimeField;
            }
            set {
                this.destinationtimeField = value;
                this.RaisePropertyChanged("Destinationtime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Lastlocation {
            get {
                return this.lastlocationField;
            }
            set {
                this.lastlocationField = value;
                this.RaisePropertyChanged("Lastlocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int Duein {
            get {
                return this.dueinField;
            }
            set {
                this.dueinField = value;
                this.RaisePropertyChanged("Duein");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Late {
            get {
                return this.lateField;
            }
            set {
                this.lateField = value;
                this.RaisePropertyChanged("Late");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Exparrival {
            get {
                return this.exparrivalField;
            }
            set {
                this.exparrivalField = value;
                this.RaisePropertyChanged("Exparrival");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Expdepart {
            get {
                return this.expdepartField;
            }
            set {
                this.expdepartField = value;
                this.RaisePropertyChanged("Expdepart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Scharrival {
            get {
                return this.scharrivalField;
            }
            set {
                this.scharrivalField = value;
                this.RaisePropertyChanged("Scharrival");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Schdepart {
            get {
                return this.schdepartField;
            }
            set {
                this.schdepartField = value;
                this.RaisePropertyChanged("Schdepart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Traintype {
            get {
                return this.traintypeField;
            }
            set {
                this.traintypeField = value;
                this.RaisePropertyChanged("Traintype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Locationtype {
            get {
                return this.locationtypeField;
            }
            set {
                this.locationtypeField = value;
                this.RaisePropertyChanged("Locationtype");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objTrainPositions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string trainStatusField;
        
        private string trainLatitudeField;
        
        private string trainLongitudeField;
        
        private string trainCodeField;
        
        private string trainDateField;
        
        private string publicMessageField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TrainStatus {
            get {
                return this.trainStatusField;
            }
            set {
                this.trainStatusField = value;
                this.RaisePropertyChanged("TrainStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TrainLatitude {
            get {
                return this.trainLatitudeField;
            }
            set {
                this.trainLatitudeField = value;
                this.RaisePropertyChanged("TrainLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TrainLongitude {
            get {
                return this.trainLongitudeField;
            }
            set {
                this.trainLongitudeField = value;
                this.RaisePropertyChanged("TrainLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TrainCode {
            get {
                return this.trainCodeField;
            }
            set {
                this.trainCodeField = value;
                this.RaisePropertyChanged("TrainCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TrainDate {
            get {
                return this.trainDateField;
            }
            set {
                this.trainDateField = value;
                this.RaisePropertyChanged("TrainDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PublicMessage {
            get {
                return this.publicMessageField;
            }
            set {
                this.publicMessageField = value;
                this.RaisePropertyChanged("PublicMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.irishrail.ie/realtime/")]
    public partial class objHaconPositions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string trainStatusField;
        
        private string trainLatitudeField;
        
        private string trainLongitudeField;
        
        private string trainCodeField;
        
        private string trainDateField;
        
        private string lastLocationTypeField;
        
        private string directionField;
        
        private string trainOriginField;
        
        private string trainOriginTimeField;
        
        private string trainDestinationField;
        
        private string trainDestinationTimeField;
        
        private string lastLocationField;
        
        private string nextLocationField;
        
        private string differenceField;
        
        private string scheduledDepartureField;
        
        private string scheduledArrivalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TrainStatus {
            get {
                return this.trainStatusField;
            }
            set {
                this.trainStatusField = value;
                this.RaisePropertyChanged("TrainStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TrainLatitude {
            get {
                return this.trainLatitudeField;
            }
            set {
                this.trainLatitudeField = value;
                this.RaisePropertyChanged("TrainLatitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TrainLongitude {
            get {
                return this.trainLongitudeField;
            }
            set {
                this.trainLongitudeField = value;
                this.RaisePropertyChanged("TrainLongitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TrainCode {
            get {
                return this.trainCodeField;
            }
            set {
                this.trainCodeField = value;
                this.RaisePropertyChanged("TrainCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TrainDate {
            get {
                return this.trainDateField;
            }
            set {
                this.trainDateField = value;
                this.RaisePropertyChanged("TrainDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LastLocationType {
            get {
                return this.lastLocationTypeField;
            }
            set {
                this.lastLocationTypeField = value;
                this.RaisePropertyChanged("LastLocationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
                this.RaisePropertyChanged("Direction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TrainOrigin {
            get {
                return this.trainOriginField;
            }
            set {
                this.trainOriginField = value;
                this.RaisePropertyChanged("TrainOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TrainOriginTime {
            get {
                return this.trainOriginTimeField;
            }
            set {
                this.trainOriginTimeField = value;
                this.RaisePropertyChanged("TrainOriginTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TrainDestination {
            get {
                return this.trainDestinationField;
            }
            set {
                this.trainDestinationField = value;
                this.RaisePropertyChanged("TrainDestination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TrainDestinationTime {
            get {
                return this.trainDestinationTimeField;
            }
            set {
                this.trainDestinationTimeField = value;
                this.RaisePropertyChanged("TrainDestinationTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string LastLocation {
            get {
                return this.lastLocationField;
            }
            set {
                this.lastLocationField = value;
                this.RaisePropertyChanged("LastLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string NextLocation {
            get {
                return this.nextLocationField;
            }
            set {
                this.nextLocationField = value;
                this.RaisePropertyChanged("NextLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Difference {
            get {
                return this.differenceField;
            }
            set {
                this.differenceField = value;
                this.RaisePropertyChanged("Difference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ScheduledDeparture {
            get {
                return this.scheduledDepartureField;
            }
            set {
                this.scheduledDepartureField = value;
                this.RaisePropertyChanged("ScheduledDeparture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ScheduledArrival {
            get {
                return this.scheduledArrivalField;
            }
            set {
                this.scheduledArrivalField = value;
                this.RaisePropertyChanged("ScheduledArrival");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllStationsXML_WithStationType", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getAllStationsXML_WithStationType {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public string StationType;
        
        public getAllStationsXML_WithStationType() {
        }
        
        public getAllStationsXML_WithStationType(string StationType) {
            this.StationType = StationType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllStationsXML_WithStationTypeResponse", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getAllStationsXML_WithStationType1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public BusGoBackHome.TrainTimeResult.objStation[] getAllStationsXML_WithStationTypeResult;
        
        public getAllStationsXML_WithStationType1() {
        }
        
        public getAllStationsXML_WithStationType1(BusGoBackHome.TrainTimeResult.objStation[] getAllStationsXML_WithStationTypeResult) {
            this.getAllStationsXML_WithStationTypeResult = getAllStationsXML_WithStationTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentTrainsXML_WithTrainType", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getCurrentTrainsXML_WithTrainType {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public string TrainType;
        
        public getCurrentTrainsXML_WithTrainType() {
        }
        
        public getCurrentTrainsXML_WithTrainType(string TrainType) {
            this.TrainType = TrainType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentTrainsXML_WithTrainTypeResponse", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getCurrentTrainsXML_WithTrainType1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public BusGoBackHome.TrainTimeResult.objTrainPositions[] getCurrentTrainsXML_WithTrainTypeResult;
        
        public getCurrentTrainsXML_WithTrainType1() {
        }
        
        public getCurrentTrainsXML_WithTrainType1(BusGoBackHome.TrainTimeResult.objTrainPositions[] getCurrentTrainsXML_WithTrainTypeResult) {
            this.getCurrentTrainsXML_WithTrainTypeResult = getCurrentTrainsXML_WithTrainTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByNameXML_withNumMins", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByNameXML_withNumMins {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public string StationDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=1)]
        public string NumMins;
        
        public getStationDataByNameXML_withNumMins() {
        }
        
        public getStationDataByNameXML_withNumMins(string StationDesc, string NumMins) {
            this.StationDesc = StationDesc;
            this.NumMins = NumMins;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByNameXML_withNumMinsResponse", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByNameXML_withNumMins1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByNameXML_withNumMinsResult;
        
        public getStationDataByNameXML_withNumMins1() {
        }
        
        public getStationDataByNameXML_withNumMins1(BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByNameXML_withNumMinsResult) {
            this.getStationDataByNameXML_withNumMinsResult = getStationDataByNameXML_withNumMinsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByNameXML", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByNameXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public string StationDesc;
        
        public getStationDataByNameXMLRequest() {
        }
        
        public getStationDataByNameXMLRequest(string StationDesc) {
            this.StationDesc = StationDesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByNameXMLResponse", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByNameXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByNameXMLResult;
        
        public getStationDataByNameXMLResponse() {
        }
        
        public getStationDataByNameXMLResponse(BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByNameXMLResult) {
            this.getStationDataByNameXMLResult = getStationDataByNameXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByCodeXML_WithNumMins", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByCodeXML_WithNumMins {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public string StationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=1)]
        public string NumMins;
        
        public getStationDataByCodeXML_WithNumMins() {
        }
        
        public getStationDataByCodeXML_WithNumMins(string StationCode, string NumMins) {
            this.StationCode = StationCode;
            this.NumMins = NumMins;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStationDataByCodeXML_WithNumMinsResponse", WrapperNamespace="http://api.irishrail.ie/realtime/", IsWrapped=true)]
    public partial class getStationDataByCodeXML_WithNumMins1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.irishrail.ie/realtime/", Order=0)]
        public BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByCodeXML_WithNumMinsResult;
        
        public getStationDataByCodeXML_WithNumMins1() {
        }
        
        public getStationDataByCodeXML_WithNumMins1(BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByCodeXML_WithNumMinsResult) {
            this.getStationDataByCodeXML_WithNumMinsResult = getStationDataByCodeXML_WithNumMinsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RealtimeSoapChannel : BusGoBackHome.TrainTimeResult.RealtimeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealtimeSoapClient : System.ServiceModel.ClientBase<BusGoBackHome.TrainTimeResult.RealtimeSoap>, BusGoBackHome.TrainTimeResult.RealtimeSoap {
        
        public RealtimeSoapClient() {
        }
        
        public RealtimeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealtimeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealtimeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealtimeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BusGoBackHome.TrainTimeResult.objStation[] getAllStationsXML() {
            return base.Channel.getAllStationsXML();
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objStation[]> getAllStationsXMLAsync() {
            return base.Channel.getAllStationsXMLAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType1 BusGoBackHome.TrainTimeResult.RealtimeSoap.getAllStationsXML1(BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType request) {
            return base.Channel.getAllStationsXML1(request);
        }
        
        public BusGoBackHome.TrainTimeResult.objStation[] getAllStationsXML1(string StationType) {
            BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType inValue = new BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType();
            inValue.StationType = StationType;
            BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType1 retVal = ((BusGoBackHome.TrainTimeResult.RealtimeSoap)(this)).getAllStationsXML1(inValue);
            return retVal.getAllStationsXML_WithStationTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType1> BusGoBackHome.TrainTimeResult.RealtimeSoap.getAllStationsXML1Async(BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType request) {
            return base.Channel.getAllStationsXML1Async(request);
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType1> getAllStationsXML1Async(string StationType) {
            BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType inValue = new BusGoBackHome.TrainTimeResult.getAllStationsXML_WithStationType();
            inValue.StationType = StationType;
            return ((BusGoBackHome.TrainTimeResult.RealtimeSoap)(this)).getAllStationsXML1Async(inValue);
        }
        
        public BusGoBackHome.TrainTimeResult.objHaconPositions[] getHaconTrainsXML() {
            return base.Channel.getHaconTrainsXML();
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objHaconPositions[]> getHaconTrainsXMLAsync() {
            return base.Channel.getHaconTrainsXMLAsync();
        }
        
        public BusGoBackHome.TrainTimeResult.objTrainPositions[] getCurrentTrainsXML() {
            return base.Channel.getCurrentTrainsXML();
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objTrainPositions[]> getCurrentTrainsXMLAsync() {
            return base.Channel.getCurrentTrainsXMLAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType1 BusGoBackHome.TrainTimeResult.RealtimeSoap.getCurrentTrainsXML1(BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType request) {
            return base.Channel.getCurrentTrainsXML1(request);
        }
        
        public BusGoBackHome.TrainTimeResult.objTrainPositions[] getCurrentTrainsXML1(string TrainType) {
            BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType inValue = new BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType();
            inValue.TrainType = TrainType;
            BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType1 retVal = ((BusGoBackHome.TrainTimeResult.RealtimeSoap)(this)).getCurrentTrainsXML1(inValue);
            return retVal.getCurrentTrainsXML_WithTrainTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType1> BusGoBackHome.TrainTimeResult.RealtimeSoap.getCurrentTrainsXML1Async(BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType request) {
            return base.Channel.getCurrentTrainsXML1Async(request);
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType1> getCurrentTrainsXML1Async(string TrainType) {
            BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType inValue = new BusGoBackHome.TrainTimeResult.getCurrentTrainsXML_WithTrainType();
            inValue.TrainType = TrainType;
            return ((BusGoBackHome.TrainTimeResult.RealtimeSoap)(this)).getCurrentTrainsXML1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins1 BusGoBackHome.TrainTimeResult.RealtimeSoap.getStationDataByNameXML(BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins request) {
            return base.Channel.getStationDataByNameXML(request);
        }
        
        public BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByNameXML(string StationDesc, string NumMins) {
            BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins inValue = new BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins();
            inValue.StationDesc = StationDesc;
            inValue.NumMins = NumMins;
            BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins1 retVal = ((BusGoBackHome.TrainTimeResult.RealtimeSoap)(this)).getStationDataByNameXML(inValue);
            return retVal.getStationDataByNameXML_withNumMinsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins1> BusGoBackHome.TrainTimeResult.RealtimeSoap.getStationDataByNameXMLAsync(BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins request) {
            return base.Channel.getStationDataByNameXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins1> getStationDataByNameXMLAsync(string StationDesc, string NumMins) {
            BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins inValue = new BusGoBackHome.TrainTimeResult.getStationDataByNameXML_withNumMins();
            inValue.StationDesc = StationDesc;
            inValue.NumMins = NumMins;
            return ((BusGoBackHome.TrainTimeResult.RealtimeSoap)(this)).getStationDataByNameXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusGoBackHome.TrainTimeResult.getStationDataByNameXMLResponse BusGoBackHome.TrainTimeResult.RealtimeSoap.getStationDataByNameXML1(BusGoBackHome.TrainTimeResult.getStationDataByNameXMLRequest request) {
            return base.Channel.getStationDataByNameXML1(request);
        }
        
        public BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByNameXML1(string StationDesc) {
            BusGoBackHome.TrainTimeResult.getStationDataByNameXMLRequest inValue = new BusGoBackHome.TrainTimeResult.getStationDataByNameXMLRequest();
            inValue.StationDesc = StationDesc;
            BusGoBackHome.TrainTimeResult.getStationDataByNameXMLResponse retVal = ((BusGoBackHome.TrainTimeResult.RealtimeSoap)(this)).getStationDataByNameXML1(inValue);
            return retVal.getStationDataByNameXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getStationDataByNameXMLResponse> BusGoBackHome.TrainTimeResult.RealtimeSoap.getStationDataByNameXML1Async(BusGoBackHome.TrainTimeResult.getStationDataByNameXMLRequest request) {
            return base.Channel.getStationDataByNameXML1Async(request);
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getStationDataByNameXMLResponse> getStationDataByNameXML1Async(string StationDesc) {
            BusGoBackHome.TrainTimeResult.getStationDataByNameXMLRequest inValue = new BusGoBackHome.TrainTimeResult.getStationDataByNameXMLRequest();
            inValue.StationDesc = StationDesc;
            return ((BusGoBackHome.TrainTimeResult.RealtimeSoap)(this)).getStationDataByNameXML1Async(inValue);
        }
        
        public BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByCodeXML(string StationCode) {
            return base.Channel.getStationDataByCodeXML(StationCode);
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objStationData[]> getStationDataByCodeXMLAsync(string StationCode) {
            return base.Channel.getStationDataByCodeXMLAsync(StationCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins1 BusGoBackHome.TrainTimeResult.RealtimeSoap.getStationDataByCodeXML1(BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins request) {
            return base.Channel.getStationDataByCodeXML1(request);
        }
        
        public BusGoBackHome.TrainTimeResult.objStationData[] getStationDataByCodeXML1(string StationCode, string NumMins) {
            BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins inValue = new BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins();
            inValue.StationCode = StationCode;
            inValue.NumMins = NumMins;
            BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins1 retVal = ((BusGoBackHome.TrainTimeResult.RealtimeSoap)(this)).getStationDataByCodeXML1(inValue);
            return retVal.getStationDataByCodeXML_WithNumMinsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins1> BusGoBackHome.TrainTimeResult.RealtimeSoap.getStationDataByCodeXML1Async(BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins request) {
            return base.Channel.getStationDataByCodeXML1Async(request);
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins1> getStationDataByCodeXML1Async(string StationCode, string NumMins) {
            BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins inValue = new BusGoBackHome.TrainTimeResult.getStationDataByCodeXML_WithNumMins();
            inValue.StationCode = StationCode;
            inValue.NumMins = NumMins;
            return ((BusGoBackHome.TrainTimeResult.RealtimeSoap)(this)).getStationDataByCodeXML1Async(inValue);
        }
        
        public BusGoBackHome.TrainTimeResult.objStationFilter[] getStationsFilterXML(string StationText) {
            return base.Channel.getStationsFilterXML(StationText);
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objStationFilter[]> getStationsFilterXMLAsync(string StationText) {
            return base.Channel.getStationsFilterXMLAsync(StationText);
        }
        
        public BusGoBackHome.TrainTimeResult.objTrainMovements[] getTrainMovementsXML(string TrainId, string TrainDate) {
            return base.Channel.getTrainMovementsXML(TrainId, TrainDate);
        }
        
        public System.Threading.Tasks.Task<BusGoBackHome.TrainTimeResult.objTrainMovements[]> getTrainMovementsXMLAsync(string TrainId, string TrainDate) {
            return base.Channel.getTrainMovementsXMLAsync(TrainId, TrainDate);
        }
    }
}
