//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DublinBus
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dublinbus.ie/", ConfigurationName="DublinBus.DublinBusRTPIServiceSoap")]
    public interface DublinBusRTPIServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/TestService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TestServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetRealTimeStopData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.GetRealTimeStopDataResponseGetRealTimeStopDataResult> GetRealTimeStopDataAsync(int stopId, bool forceRefresh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetRealTimeStopData_ForceLineNoteVisit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.GetRealTimeStopData_ForceLineNoteVisitResponseGetRealTimeStopData_ForceLineNoteVisitResult> GetRealTimeStopData_ForceLineNoteVisitAsync(int stopId, bool forceRefresh, bool forceLineNoteVisit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetRoutes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.RoutesResponse> GetRoutesAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetRoutesIncNiteLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.RoutesResponse> GetRoutesIncNiteLinkAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetRoutesIncNiteLink_MobileFareCalc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.RoutesResponse> GetRoutesIncNiteLink_MobileFareCalcAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetDestinations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.DestinationsResponse> GetDestinationsAsync(string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetAllDestinations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.DestinationsResponse> GetAllDestinationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetStopDataByAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.GetStopDataByAddressResponseGetStopDataByAddressResult> GetStopDataByAddressAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetStopDataByRouteAndDirection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.GetStopDataByRouteAndDirectionResponseGetStopDataByRouteAndDirectionResult> GetStopDataByRouteAndDirectionAsync(string route, string direction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetStopDataByRouteAndDirection_MobileFareCalc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.GetStopDataByRouteAndDirection_MobileFareCalcResponseGetStopDataByRouteAndDirection_MobileFareCalcResult> GetStopDataByRouteAndDirection_MobileFareCalcAsync(string route, string direction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetStopDataByRoute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.ArrayOfXElement> GetStopDataByRouteAsync(string route);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetRoutesServicedByStopNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DublinBus.Route[]> GetRoutesServicedByStopNumberAsync(int stopId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/StartTimer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> StartTimerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/StopTimer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> StopTimerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/GetCurrentSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string[]> GetCurrentSettingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/SetCurrentSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task SetCurrentSettingsAsync(string[] values);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/postXMLData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> postXMLDataAsync(string destinationUrl, string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dublinbus.ie/ClearCacheItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> ClearCacheItemAsync(string key);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dublinbus.ie/")]
    public partial class GetRealTimeStopDataResponseGetRealTimeStopDataResult
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dublinbus.ie/")]
    public partial class DestinationsResponse
    {
        
        private Destination[] destinationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Destination[] Destinations
        {
            get
            {
                return this.destinationsField;
            }
            set
            {
                this.destinationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dublinbus.ie/")]
    public partial class Destination
    {
        
        private int stopNumberField;
        
        private string typeField;
        
        private double longitudeField;
        
        private double latitudeField;
        
        private string descriptionField;
        
        private Route[] routesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int StopNumber
        {
            get
            {
                return this.stopNumberField;
            }
            set
            {
                this.stopNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public Route[] Routes
        {
            get
            {
                return this.routesField;
            }
            set
            {
                this.routesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dublinbus.ie/")]
    public partial class Route
    {
        
        private string numberField;
        
        private string directionField;
        
        private int seqNumberField;
        
        private string towardsField;
        
        private string fromField;
        
        private Destination[] destinationsField;
        
        private string descriptionField;
        
        private bool isStagedField;
        
        private string outboundPatternField;
        
        private string outboundFromField;
        
        private string outboundTowardsField;
        
        private string outboundViaField;
        
        private string inboundPatternField;
        
        private string inboundFromField;
        
        private string inboundTowardsField;
        
        private string inboundViaField;
        
        private bool isXpressoField;
        
        private bool isNitelinkField;
        
        private bool isMinimumFareField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SeqNumber
        {
            get
            {
                return this.seqNumberField;
            }
            set
            {
                this.seqNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Towards
        {
            get
            {
                return this.towardsField;
            }
            set
            {
                this.towardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Destinations", IsNullable=true, Order=5)]
        public Destination[] Destinations
        {
            get
            {
                return this.destinationsField;
            }
            set
            {
                this.destinationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsStaged
        {
            get
            {
                return this.isStagedField;
            }
            set
            {
                this.isStagedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OutboundPattern
        {
            get
            {
                return this.outboundPatternField;
            }
            set
            {
                this.outboundPatternField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string OutboundFrom
        {
            get
            {
                return this.outboundFromField;
            }
            set
            {
                this.outboundFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string OutboundTowards
        {
            get
            {
                return this.outboundTowardsField;
            }
            set
            {
                this.outboundTowardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string OutboundVia
        {
            get
            {
                return this.outboundViaField;
            }
            set
            {
                this.outboundViaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string InboundPattern
        {
            get
            {
                return this.inboundPatternField;
            }
            set
            {
                this.inboundPatternField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string InboundFrom
        {
            get
            {
                return this.inboundFromField;
            }
            set
            {
                this.inboundFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string InboundTowards
        {
            get
            {
                return this.inboundTowardsField;
            }
            set
            {
                this.inboundTowardsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string InboundVia
        {
            get
            {
                return this.inboundViaField;
            }
            set
            {
                this.inboundViaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool IsXpresso
        {
            get
            {
                return this.isXpressoField;
            }
            set
            {
                this.isXpressoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool IsNitelink
        {
            get
            {
                return this.isNitelinkField;
            }
            set
            {
                this.isNitelinkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool IsMinimumFare
        {
            get
            {
                return this.isMinimumFareField;
            }
            set
            {
                this.isMinimumFareField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dublinbus.ie/")]
    public partial class RoutesResponse
    {
        
        private Route[] routesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Route[] Routes
        {
            get
            {
                return this.routesField;
            }
            set
            {
                this.routesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dublinbus.ie/")]
    public partial class GetRealTimeStopData_ForceLineNoteVisitResponseGetRealTimeStopData_ForceLineNoteVisitResult
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dublinbus.ie/")]
    public partial class GetStopDataByAddressResponseGetStopDataByAddressResult
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dublinbus.ie/")]
    public partial class GetStopDataByRouteAndDirectionResponseGetStopDataByRouteAndDirectionResult
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dublinbus.ie/")]
    public partial class GetStopDataByRouteAndDirection_MobileFareCalcResponseGetStopDataByRouteAndDirection_MobileFareCalcResult
    {
        
        private System.Xml.Linq.XElement[] anyField;
        
        private System.Xml.Linq.XElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface DublinBusRTPIServiceSoapChannel : DublinBus.DublinBusRTPIServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class DublinBusRTPIServiceSoapClient : System.ServiceModel.ClientBase<DublinBus.DublinBusRTPIServiceSoap>, DublinBus.DublinBusRTPIServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DublinBusRTPIServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DublinBusRTPIServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), DublinBusRTPIServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DublinBusRTPIServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DublinBusRTPIServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DublinBusRTPIServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DublinBusRTPIServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DublinBusRTPIServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> TestServiceAsync()
        {
            return base.Channel.TestServiceAsync();
        }
        
        public System.Threading.Tasks.Task<DublinBus.GetRealTimeStopDataResponseGetRealTimeStopDataResult> GetRealTimeStopDataAsync(int stopId, bool forceRefresh)
        {
            return base.Channel.GetRealTimeStopDataAsync(stopId, forceRefresh);
        }
        
        public System.Threading.Tasks.Task<DublinBus.GetRealTimeStopData_ForceLineNoteVisitResponseGetRealTimeStopData_ForceLineNoteVisitResult> GetRealTimeStopData_ForceLineNoteVisitAsync(int stopId, bool forceRefresh, bool forceLineNoteVisit)
        {
            return base.Channel.GetRealTimeStopData_ForceLineNoteVisitAsync(stopId, forceRefresh, forceLineNoteVisit);
        }
        
        public System.Threading.Tasks.Task<DublinBus.RoutesResponse> GetRoutesAsync(string filter)
        {
            return base.Channel.GetRoutesAsync(filter);
        }
        
        public System.Threading.Tasks.Task<DublinBus.RoutesResponse> GetRoutesIncNiteLinkAsync(string filter)
        {
            return base.Channel.GetRoutesIncNiteLinkAsync(filter);
        }
        
        public System.Threading.Tasks.Task<DublinBus.RoutesResponse> GetRoutesIncNiteLink_MobileFareCalcAsync(string filter)
        {
            return base.Channel.GetRoutesIncNiteLink_MobileFareCalcAsync(filter);
        }
        
        public System.Threading.Tasks.Task<DublinBus.DestinationsResponse> GetDestinationsAsync(string filter)
        {
            return base.Channel.GetDestinationsAsync(filter);
        }
        
        public System.Threading.Tasks.Task<DublinBus.DestinationsResponse> GetAllDestinationsAsync()
        {
            return base.Channel.GetAllDestinationsAsync();
        }
        
        public System.Threading.Tasks.Task<DublinBus.GetStopDataByAddressResponseGetStopDataByAddressResult> GetStopDataByAddressAsync(string address)
        {
            return base.Channel.GetStopDataByAddressAsync(address);
        }
        
        public System.Threading.Tasks.Task<DublinBus.GetStopDataByRouteAndDirectionResponseGetStopDataByRouteAndDirectionResult> GetStopDataByRouteAndDirectionAsync(string route, string direction)
        {
            return base.Channel.GetStopDataByRouteAndDirectionAsync(route, direction);
        }
        
        public System.Threading.Tasks.Task<DublinBus.GetStopDataByRouteAndDirection_MobileFareCalcResponseGetStopDataByRouteAndDirection_MobileFareCalcResult> GetStopDataByRouteAndDirection_MobileFareCalcAsync(string route, string direction)
        {
            return base.Channel.GetStopDataByRouteAndDirection_MobileFareCalcAsync(route, direction);
        }
        
        public System.Threading.Tasks.Task<DublinBus.ArrayOfXElement> GetStopDataByRouteAsync(string route)
        {
            return base.Channel.GetStopDataByRouteAsync(route);
        }
        
        public System.Threading.Tasks.Task<DublinBus.Route[]> GetRoutesServicedByStopNumberAsync(int stopId)
        {
            return base.Channel.GetRoutesServicedByStopNumberAsync(stopId);
        }
        
        public System.Threading.Tasks.Task<bool> StartTimerAsync()
        {
            return base.Channel.StartTimerAsync();
        }
        
        public System.Threading.Tasks.Task<bool> StopTimerAsync()
        {
            return base.Channel.StopTimerAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCurrentSettingsAsync()
        {
            return base.Channel.GetCurrentSettingsAsync();
        }
        
        public System.Threading.Tasks.Task SetCurrentSettingsAsync(string[] values)
        {
            return base.Channel.SetCurrentSettingsAsync(values);
        }
        
        public System.Threading.Tasks.Task<string> postXMLDataAsync(string destinationUrl, string requestXml)
        {
            return base.Channel.postXMLDataAsync(destinationUrl, requestXml);
        }
        
        public System.Threading.Tasks.Task<bool> ClearCacheItemAsync(string key)
        {
            return base.Channel.ClearCacheItemAsync(key);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DublinBusRTPIServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DublinBusRTPIServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DublinBusRTPIServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://rtpi.dublinbus.ie/DublinBusRTPIService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DublinBusRTPIServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://rtpi.dublinbus.ie/DublinBusRTPIService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DublinBusRTPIServiceSoap,
            
            DublinBusRTPIServiceSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
